name: teste
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2  #####
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  flutter_local_notifications: ^17.2.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  local_auth: ^2.1.6
  share_plus: ^10.0.0
  permission_handler: ^11.3.0
  

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/pagina2.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
  assets:
    - assets/icon/icon.png
    - assets/icon/pagina2.png
    - assets/images/calendario.png
    - assets/images/ConfigPerfil.png
    - assets/images/iconeSemFundo.png